### ISSUE TITLE
Updating to elasticsearch 5.5.1

### ISSUE THREAD

**Issue by mdaley** [GoogleCloudPlatform/elasticsearch-docker#10]
Hello I wanted to have a version of this repository updated to elasticsearch 5.5.1, the latest stable release.  The changes in my fork (see link below) work for me so I hope they are OK?  However, I don't know how to run the functional_tests?  Could you advise me?  Thanks.

https://github.com/mdaley/elasticsearch-docker/commit/d758d2d7a44de3d97b4d1bb8fabd59078202b55f

If these changes are right, I could sign the CLA and create a pull request.  If not right, please advise me what to change?  Hope that's all OK...

Matt

**Comment by jprzychodzen** [comment]
Thank you for submitting this issue. We are currently working on adding support for 5.5.x. We will update this issue once it is available.

**Comment by jprzychodzen** [comment]
Elasticsearch is updated to 5.5.1.
