### ISSUE TITLE
GCP Command Depreciation: Change documentation

### ISSUE THREAD

**Issue by skviknesh** [GoogleCloudPlatform/elasticsearch-docker#26]
Hi Team,

Just thought of saying this... There is a warning while pulling elastic-search image following the document.
```
gcloud docker -- pull launcher.gcr.io/google/elasticsearch6
```

**WARNING: `gcloud docker` will not be supported for Docker client versions above 18.03.**

As an alternative, use `gcloud auth configure-docker` to configure `docker` to
use `gcloud` as a credential helper, then use `docker` as you would for non-GCR
registries, e.g. `docker pull gcr.io/project-id/my-image`. Add
`--verbosity=error` to silence this warning: `gcloud docker
--verbosity=error -- pull gcr.io/project-id/my-image`.

See: https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker

**Can you change the document available in elastic-search/6/README.md** file?

**Comment by ekorolevich** [comment]
Done.

commit: f2a731a3d31c76e0649d9d9c219ac26f96aa098b

**Comment by armandomiani** [comment]
Nice catch @skviknesh . Additionally the README has been moved to the repo root.

Thank you for your contribution.
