### ISSUE TITLE
Cannot run the Elasticsearch on Kubernetes with the instruction

### ISSUE THREAD

**Issue by duchnguyen** [GoogleCloudPlatform/elasticsearch-docker#40]
Hi,

I follow the [README](https://github.com/GoogleCloudPlatform/elasticsearch-docker/blob/master/5/README.md) to deploy elasticsearch on Kubernetes. Here are my steps 

1. Copy the following content to pod.yaml file
<pre>
apiVersion: v1
kind: Pod
metadata:
  name: some-elasticsearch
  labels:
    name: some-elasticsearch
spec:
  containers:
    - image: launcher.gcr.io/google/elasticsearch5
      name: elasticsearch
</pre>

2. Run kubectl create -f pod.yaml.

-> The pod cannot be started successfully because of below error. 

![es_error](https://user-images.githubusercontent.com/38968649/41150691-d2778688-6b38-11e8-932d-9080809455ac.png)

Please help guide me how to deploy it

Thanks,
Duc

**Comment by duchnguyen** [comment]
Hi Kamil,

Thanks for your help. I included the sysctl command in manifest file (below) but still couldn't start the service. I also don't find any useful information in log tab - below.

<pre>
apiVersion: v1
kind: Pod
metadata:
  name: some-elasticsearch
  labels:
    name: some-elasticsearch
spec:
  initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
  containers:
    - image: launcher.gcr.io/google/elasticsearch5
      name: elasticsearch
</pre>

Here is log tab info 

![es-log](https://user-images.githubusercontent.com/38968649/41154899-ecbeb180-6b45-11e8-8112-160d8711658f.png)
  

Thanks,
Duc

**Comment by khajduczenia** [comment]
The manifest is correct. In your screenshot there is error saying: `OOMKilled with exit code 137` - it looks like you might not have enough resources allocated on your GKE cluster. You might have too much load already when deploying your Elasticsearch pod or your VM instances don't have enough memory.

Can you try the deployment on a cluster with increased resources?

**Comment by duchnguyen** [comment]
Thanks Kamil. I successfully deployed the elasticsearch in Kubernetes with a strong node. And now, I'm trying to deploy a *elasticsearch cluster* on Kubernetes. If I run into any issue, please help. 

Thanks,
Duc

**Comment by duchnguyen** [comment]
Hi Kamil,

Is there any way to restrict access after deploying ES in Kubernetes?

Thanks,
Duc
