### ISSUE TITLE
Cannot run image after successful build: "exec: \"/docker-entrypoint.sh\": permission denied"

### ISSUE THREAD

**Issue by ADBalici** [GoogleCloudPlatform/elasticsearch-docker#48]
Tried building the image using the supplied Dockerfile (attempted this on multiple image versions, including 6.3). The build was successful.

However, when trying to run the image on my local Docker engine, I am getting this error:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied": unknown.
ERRO[0003] error waiting for container: context canceled`

The command I've used to run this was:

`$ docker run -a STDOUT --privileged=true elasticsearch`
(image was named elasticserch during the build step)

After further investigation, it seems that a one line change in the Dockerfile can solve the problem:
```
[...]
VOLUME /usr/share/elasticsearch/data

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh <------------ THIS

EXPOSE 9200 9300
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["elasticsearch"]
```
Running the image after rebuilding it with that additions seems to work fine:

```
[2018-09-19T14:04:38,906][INFO ][o.e.n.Node               ] [] initializing ...
[2018-09-19T14:04:39,017][INFO ][o.e.e.NodeEnvironment    ] [06419Uq] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda2)]], net usable_space [472.5gb], net total_space [908.5gb], types [ext4]
[...]
[2018-09-19T14:04:44,798][INFO ][o.e.n.Node               ] [06419Uq] started
[2018-09-19T14:04:44,854][INFO ][o.e.g.GatewayService     ] [06419Uq] recovered [0] indices into cluster_state
```

Is this an actual bug or am I attempting to run the image in the wrong way?
Thanks,

**Comment by jprzychodzen** [comment]
Thank you for submitting this issue. Could check file permissions for cloned repository and provide your umask setting?
```
# Create tmp directory
TEMPORARY_DIR=$(mktemp -d)
cd $TEMPORARY_DIR
# Clone repository
git clone  https://github.com/GoogleCloudPlatform/elasticsearch-docker.git
# Check permissions for existing files
echo "Permissions:"
find elasticsearch-docker -name docker-entrypoint.sh -exec ls -al {} \;
# Print umask
echo -n "UMASK: "
umask
```

**Comment by jprzychodzen** [comment]
Closing as no response was received.
